// <auto-generated />
using System;
using Back;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Back.Migrations
{
    [DbContext(typeof(BaseDeDatosApp))]
    [Migration("20231023203542_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Back.Agenda", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("fechaHora")
                        .HasColumnType("datetime2");

                    b.Property<int>("medicoAgendaid")
                        .HasColumnType("int");

                    b.Property<string>("paciente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("medicoAgendaid");

                    b.ToTable("Agendas");
                });

            modelBuilder.Entity("Back.Especialidad", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Especialidades");
                });

            modelBuilder.Entity("Back.Historial", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("dni")
                        .HasColumnType("int");

                    b.Property<DateTime>("fechaHora")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("fechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("obraSocial")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Historiales");
                });

            modelBuilder.Entity("Back.Persona", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("dni")
                        .HasColumnType("int");

                    b.Property<DateTime>("fechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Personas");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Persona");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Back.Turno", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("fechaHora")
                        .HasColumnType("datetime2");

                    b.Property<int>("medicoTurnoid")
                        .HasColumnType("int");

                    b.Property<int>("pacienteTurnoid")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("medicoTurnoid");

                    b.HasIndex("pacienteTurnoid");

                    b.ToTable("Turnos");
                });

            modelBuilder.Entity("Back.Usuario", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("contrasenia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("correo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Back.Medico", b =>
                {
                    b.HasBaseType("Back.Persona");

                    b.Property<string>("contrasenia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("correo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("especialidadid")
                        .HasColumnType("int");

                    b.Property<string>("matriculaMedico")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasIndex("especialidadid");

                    b.HasDiscriminator().HasValue("Medico");
                });

            modelBuilder.Entity("Back.Paciente", b =>
                {
                    b.HasBaseType("Back.Persona");

                    b.Property<int>("idpaciente")
                        .HasColumnType("int");

                    b.Property<double>("vacunasAlDia")
                        .HasColumnType("float");

                    b.HasDiscriminator().HasValue("Paciente");
                });

            modelBuilder.Entity("Back.Secretaria", b =>
                {
                    b.HasBaseType("Back.Persona");

                    b.Property<int>("idSecretaria")
                        .HasColumnType("int");

                    b.Property<int>("numerolegajo")
                        .HasColumnType("int");

                    b.Property<int>("usuarioSecretariaid")
                        .HasColumnType("int");

                    b.HasIndex("usuarioSecretariaid");

                    b.HasDiscriminator().HasValue("Secretaria");
                });

            modelBuilder.Entity("Back.Agenda", b =>
                {
                    b.HasOne("Back.Medico", "medicoAgenda")
                        .WithMany()
                        .HasForeignKey("medicoAgendaid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("medicoAgenda");
                });

            modelBuilder.Entity("Back.Turno", b =>
                {
                    b.HasOne("Back.Medico", "medicoTurno")
                        .WithMany()
                        .HasForeignKey("medicoTurnoid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Back.Paciente", "pacienteTurno")
                        .WithMany()
                        .HasForeignKey("pacienteTurnoid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("medicoTurno");

                    b.Navigation("pacienteTurno");
                });

            modelBuilder.Entity("Back.Medico", b =>
                {
                    b.HasOne("Back.Especialidad", "especialidad")
                        .WithMany()
                        .HasForeignKey("especialidadid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("especialidad");
                });

            modelBuilder.Entity("Back.Secretaria", b =>
                {
                    b.HasOne("Back.Usuario", "usuarioSecretaria")
                        .WithMany()
                        .HasForeignKey("usuarioSecretariaid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("usuarioSecretaria");
                });
#pragma warning restore 612, 618
        }
    }
}
